### ISSUE TITLE
initial trigger

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-module-router#54]
I have a thoughts that Router shouldn't be triggered right after initialization. Most times we would like to fetch some initial state, check user token, etc whenever app bootstrapped. Usually it implemented in `appMounted` signal. Seems `Router(controller, routes).trigger()` and `appMounted` signal could cause a race condition or just unpredictable behavior.

Router could be triggered from `appMounted` signal, now when router exposed to services. We could also provide action for it right in lib (`import { trigger } from 'cerebral-router';`). Of course `appMounted` shouldn't be mapped to any route.

cc @christianalfoni

**Comment by NervosaX** [comment]
I've come against this exact problem. I had to create a wrapper for my router for that very reason.

Was forced to make a wrapper for it. The 
```
import Router from "cerebral-router";

export let router = null;

export const createRouter = function(controller, routes) {
	router = Router(controller, routes, {
		onlyHash: true
	});
};
```

With the eventual action:

```
import {router} from "../../../router";

export default function startRouter() {
	router.trigger();
}
```

Felt a bit wasteful.

**Comment by Guria** [comment]
@NervosaX router exposed to services: `services.router.trigger()` is available from action.

**Comment by NervosaX** [comment]
Ah, good one. In that case, my mounting signal is almost no effort as long as you don't trigger immediately.

**Comment by AidanNichol** [comment]
I'm having problems implementing this.

If in main.js I do **Router(...).trigger();** I have the race condition and it always completes before the appMounted actions.

If instead I solve the race condition, as suggested, i.e. I just create the routes **Router(..)** and add an action at the end of appMounted to do **service.router.trigger()** it works as expected. Except that on a refresh when not at **'/'** it always routes me to **'/'** rather then e.g. **'/messages'**!!

If I trigger in both places the second trigger at the end of appMounted works just fine repeating the first trigger . It sort of looks like a different sort of race condition, i.e. if I don't trigger immediately then something is getting set to a default value causing the later trigger to work differently.

**Comment by Guria** [comment]
@AidanNichol did you bound `appMounted` to router? It should be avoided.

**Comment by Guria** [comment]
Also we have plan make `router.trigger()` automatically when `Container` component from `cerebral-react` mounted.

**Comment by AidanNichol** [comment]
I don't understand what you mean by binding appMounted to router. It is probable that I'm not doing it correctly. I defined a signal and fired it explicitly
'''javascript
controller.signal('appMounted', loadTables);
controller.signals.appMounted();
Router(...)
ReactDom.render(<Container controller={controller}><App/></Container>, document.querySelector('#react'));
'''
The **loadTables** action isn't bound to any routes.

**Comment by Guria** [comment]
I have to clary some things. `appMounted` signal supposed to be triggered from `componentDidMount()`lifecycle method of your main app component. It never should be triggered again, so you shouldn't declare it at router config too. So order would be: 
* router config without trigger call
* ReactDOM.render
* componentDidMount fired for your app component
* `this.props.signals.appMounted()` got called
* actions of this signal prepares initial state
* last action calls `services.router.trigger()`

**Comment by AidanNichol** [comment]
Thanks. That makes sense. I didn't find it in the documentation but did find that line commented out in my code. I must have brought in with one of the bits that I used to get started.

However it doesn't solve my problem of refresh taking me back to ```\```

**Comment by Guria** [comment]
Share your full router config. Which signal is bound to '/'?

**Comment by AidanNichol** [comment]
I decide to make a sanity check. My code is based on [cerebral-router-demo](https://github.com/christianalfoni/cerebral-router-demo.git) so I went back and reinstalled the original in a new directory. I deleted all the cerebral items and installed them again maually to get the latest version. After tweeking the Router to get rid of the depricated message I ended up with this.

main.js
```javascript
controller.signal('appMounted', appMounted);
controller.signal('homeOpened', homeOpened);
controller.signal('messagesOpened', messagesOpened);
controller.signal('messageOpened', [...messagesOpened, ...messageOpened]);
controller.signal('invalidUrlRouted', invalidUrlRouted);

Router(controller, {
  '/': 'homeOpened',
  '/messages': 'messagesOpened',
  '/messages/:id': 'messageOpened',
  '*': 'invalidUrlRouted'
}, {
  // baseUrl: '/todomvc',
  onlyHash: true
}).trigger();

React.render(<Container controller={controller} app={App}/>, document.body);
```
I commented out the ```baseUrl``` because that caused a message **Cannot GET /todomvc** to appear as the page content!!!

Everything worked as expect. Adding
signals/appMounted.js
```javascript
import triggerLoadedRoute from './../actions/triggerLoadedRoute.js';

export default [
   triggerLoadedRoute,
];
```
and actions/triggerLoadedRoute.js
```javascript
export default function triggerLoadedRoute(input, state, output, {router}){
     router.trigger();
};
```
and
```
class App extends React.Component {
  componentDidMount() {
    this.props.signals.appMounted();
  }
```
into App.js and now the problem occurs.

**Comment by Guria** [comment]
Seems yo are still doing trigger. Remove `.trigger()` after Roter config part

**Comment by AidanNichol** [comment]
I had. I mistakenly showed you the code I started with and forgot to note that I had removed it from the Router config.

**Comment by christianalfoni** [comment]
Are we all good here? :-)

**Comment by Guria** [comment]
solved and documented in readme
