### ISSUE TITLE
convert to official cerebral module format

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-module-router#59]
I have explored converting to official cerebral module format an found some issues:

1. service method `trigger` [requires](https://github.com/cerebral/cerebral-router/blob/master/index.js#L138-L140) access to `controller`
  * `trigger` method could be registered from `init` method where we have access to `controller`
1. exporting [`redirect` action factory](https://github.com/cerebral/cerebral-router/blob/master/index.js#L172-L181) would be imposible since we have to have access to registered name
  * do not export `redirect` action factory
  * require `moduleName` to be always `router`. Check it and complain if not in `init` method

cc @christianalfoni

**Comment by bfitch** [comment]
@Guria I kind of wanted to export get() and set() action factories in the cerebral-falcor-module. I wonder if this is something modules should support

**Comment by Guria** [comment]
@bfitch we could export anything from `init` anything we want. But it would require access to `controller` in file where you define signal chains.

**Comment by Guria** [comment]
wip here: https://github.com/cerebral/cerebral-router/compare/master...modules

**Comment by christianalfoni** [comment]
I have been thinking about exposing the module name, and I believe we just have to use different strategies based on the type of module:

### Single instance module (Like router, UI lib)
1. You create a shared file between the module itself and its factories/components
2. The init method sets the name (or more) in the shared file
3. The factories/components also has access to the shared file where they can get the information set

### Multiple instance module (Like a widget, Firebase)
1. You create the module as normal
2. Any factories/components will need to be passed the module name when instantiated, like:

```js
<Widget module="widgetA"/>

const chain = [
  [FirebaseGet('firebaseA', '/some/path')]
]
```

**Comment by Guria** [comment]
@christianalfoni I have refactored to use latest `cerebral@0.29` modules API without lost of functionality. All tests grean.
Since we decided to name modules packages under `cerebral-module-*` namespace I would suggest next steps:
* keep this repo at current state to support current router registering api
* create repo for `cerebral-module-router` and init with content of [modules branch](https://github.com/cerebral/cerebral-router/compare/master...modules)

**Comment by Guria** [comment]
Also I can do `npm publish` refactored router with new name

**Comment by christianalfoni** [comment]
I completely agree! :-D

**Comment by Guria** [comment]
I have change my mind. I will rename a repo and will keep current state in a branch.
