### ISSUE TITLE
dynamic segments

### ISSUE THREAD

**Issue by eav** [cerebral/cerebral-module-router#61]
does the router support resolving dynamic segments?

**Comment by Guria** [comment]
could you explain what do you mean exactly?

**Comment by Guria** [comment]
We are using [path-to-regexp](https://github.com/pillarjs/path-to-regexp) under the hood. Just follow to it's documentation.
Consider using discord chat to ask questions: https://discord.gg/0kIweV4bd2cngbrg

**Comment by eav** [comment]
I mean when you need to load some part of the app dynamcally based on some url pattern, for example like in react-router https://github.com/rackt/react-router/tree/master/examples/dynamic-segments

ok thanks I will check that
