### ISSUE TITLE
allow redirect outside app (make app hit server)

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-module-router#73]

**Comment by christianalfoni** [comment]
It is not enough to do `location.href = "/whatever"`?

**Comment by Guria** [comment]
Do you mean it doesn't worth to have such option?

**Comment by christianalfoni** [comment]
Yeah, as I think you are "escaping" the app. It would just be a wrapper around that code anyways? We can not really bring any additional value to it? :-)

**Comment by Guria** [comment]
Yeap, it's not so hard and could be achieved with catchAll route and `location.href = "/whatever"` inside action. But @aesprice case #77 show us that not every link even on the same baseUrl should go through cerebral. I plan to make an option to not preventDefault on links that wasn't matched any signal (and there wasn't catch all route defined).
BTW, I need a good name for this option.

**Comment by Guria** [comment]
how about `allowEscape: true`?

**Comment by christianalfoni** [comment]
`allowDefault`? opposite of `preventDefault`? :)

**Comment by Guria** [comment]
Note that it is option for router:
```js
Router({
    '/': 'app.homeOpened',
    '/messages': 'app.messagesOpened',
    '/messages/:id': 'app.messageOpened',
    '/*': 'app.notFoundOpened'
  }, {
    onlyHash: true,            // use only hash part of url for matching
    // baseUrl: '/',           // base part, that ignored on route match. detected automatically if `onlyHash` option set to true
    // preventAutostart: true, // prevents automatic triggering after `modulesLoaded` event
    // allowEscape: true,      // do not prevent navigation for triggered urls if no routes was matched and catch all route wasn't provided
    // vs
    // allowDefault: true,      // do not prevent navigation for triggered urls if no routes was matched and catch all route wasn't provided
    mapper: { query: true }    // options passed to url-mapper
})
```

**Comment by christianalfoni** [comment]
Ah, hm, yeah... in this context I like your suggestion better :)
