### ISSUE TITLE
URL captured from links by RouterService seem lossy

### ISSUE THREAD

**Issue by aesprice** [cerebral/cerebral-module-router#77]
We've been working to convert a Django/jQuery application to React/Cerebral. We have a case in our app where we have a link that is not controlled by the React/Cerebral portion of our app,  but instead by the Django server. This URL tells the server to do some work, after which the server redirects the user to another page. This must be done on the backend for our application, as the work the server is doing is querying the database and changing values in the backend user session.

The URL in question is structured like so: `/some/page/path/?redirect=/server/redirects/to/some/other/page/`.

However, it looks very different when I check it in my action: `/some%2Fpage%2Fpath%2F?redirect=serverredirectstosomeotherpage/`.

The URL path, seems to be escaped (which seemed unnecessary to me) but I can handle that via `decodeURIComponent`. What I'm unable to handle is the fact that the query string's `/` characters have been completely removed, so I have no way of knowing where they belong to repair it. In my use case, this means that I can get the server to do work, but when it redirects the user, it sends them to a broken URL path.

What I'd most want would be for `RouterService.getUrl()` to actually give me the original `href` from the link, but I'd find it acceptable if whatever's transforming the query would do so in a non-lossy way.

**Comment by Guria** [comment]
`RouterService.getUrl()` does not do any encoding/decoding. It just strips out origin and baseUrl and returns routable part of current url.

From your description I can't get where exactly you takes url and where it passed then. would be great to see some snippet.

**Comment by Guria** [comment]
I really don't sure if you ever need `RouterService.getUrl()` in your case.

**Comment by aesprice** [comment]
Okay, I'll break it down a bit. I am converting a large Django application to React/Cerebral. Let's say it's hosted at `ourdomain.com/myapp/`, where some URLs are handled by our new React/cerebral client-side application, and other URLs are handled by the legacy server-side Django application.

If I have a link
```html
<a href="/myapp/some/django/path/?redirect=/myapp/server/redirects/to/some/other/page/">
```
and click it, cerebral router catches that transition.

In my router config, I have a catch-all for URLs that would take the user outside of the React/cerebral portion of our application, like this:
```js
// controller.js
Router({
    '/somepage/': 'app.some.signal',
    '/*': 'app.defaultRoute'
}, {
    mapper: {query: true},
    baseUrl: '/myapp'
})
```

That signal runs an `exitApp` actions, like so:
```js
// App/signals.js
import {exitApp} from './actions';

export default {
    defaultRoute: [exitApp]
}
```

And `exitApp looks like this:
```js
const APP_BASE_URL = '/myapp';

let exitApp = ({services}) => {
    // Capture and un-escape url path
    let externalUrl = decodeURIComponent(services.router.getUrl());
    externalUrl = APP_BASE_URL + externalUrl;

    // Force browser to navigate outside of React application
    window.location.replace(externalUrl);
};
```

When I run `services.router.getUrl()`, what is returned to me is not the `href` string: 
```js
'/myapp/some/django/path/?redirect=/myapp/server/redirects/to/some/other/page/'
```

What I actually get appears to be a mutation of it:
```js
'/myapp%2Fsome%2Fdjango%2Fpath%2F?redirect=myappserverredirectstosomeotherpage/'
```

This is not impossible to work around (as you can see in my action, I'm already using `decodeURIComponent`), but the fact that the string I get is not just encoded, but that characters are actually missing was a red flag for me, because the difference between the strings is not consistent, and characters in the query section of the URL have been removed instead of replaced.

To be clear, I recognize that my use case of converting a large server-side-rendered application to a client-side React/cerebral app is not super-common. My issue is with the (apparent) transformation of the string, and the inconsistency of it. The only thing I've done is create a link and try to access the link's URL from the router service. I have no idea what's happening in the middle.

**Comment by Guria** [comment]
@aesprice thanks, a much better now. Will try to track down it.

**Comment by Guria** [comment]
it is happens in url mapper in fact:
https://tonicdev.com/56c09ba27be58a100061e1b5/56cf4f8ad554190d00185850

what happens under the hood:
* router matches url with '/*' route and tries to parse it: path part with path-to-regexp and query part with urlon
* router calls `app.defaultRoute` with parsed value
```js
app.defaultRoute({
  "0":"myapp/some/django/path/",
  "redirect":"myappserverredirectstosomeotherpage;" 
})
```
* router stringifies back signal payload with path-to-regexp + urlon (it happens for every routable signal call to keep correct url in addressbar when signals triggered directly). usually it should match original url that triggered signal. but in your case your url was contain "malformed" query part.

I need some thoughts to suggest a best way for you to avoid this behaviour.
If I correctly understand, you have some constraints here:
* legacy server-side Django application shares the same base url as react / cerebral app and it cannot be changed
* legacy server-side urls must be rendered as `<a href="/myapp/some/django/path/?redirect=/myapp/server/redirects/to/some/other/page/">` links, so it can be right-clicked, etc
* query part can't be rewrited to match urlon format, because direct request to "/myapp/some/django/path/" will hit legacy server-side app which doesnt know anything about urlon.

Plesae confirm or deny thi points to help figure out best way to solve your case.

**Comment by Guria** [comment]
If you don't have to have escape path rendered as link the best way would be use regular not routable signal:
`<a onClick={() => { signals.app.exited({ url: '/myapp/some/django/path/?redirect=/myapp/server/redirects/to/some/other/page/' })}}/>`

**Comment by aesprice** [comment]
The list of constraints you described is correct.

As for the `onClick` approach, I did consider using this. I would prefer to stick to using the `href` for right click, hover-to-see-URL, etc, but it would fix the problem of passing the target URL to the action by explicitly setting it to `input`.

However, in our specific case, there is one additional constraint. Our React conversion did not originally use cerebral, and is actually a suite of React applications (different bundles). The component that creates these links is used in different app bundles, some of which have been converted to use cerebral, some which have not, so we can't really count on cerebral and signals being available to that component just yet.

**Comment by Guria** [comment]
@aesprice I got it. Then it can be just regular onClick handler that do exitApp stuff without going into cerebral.
I will think how to solve your problem and keep urls..

**Comment by Guria** [comment]
@aesprice I have decided to mark signals with `isRouted` option only triggered by url, so I would be able to determine when signal payload shouldn't be stringified back to addressbar. So original will be untouched.
