### ISSUE TITLE
How do I listen to every route change?

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral-module-router#90]
Hi, is there some event emitter on the router that would allow me to tap into any route change? 

Basically I'd want to use the URL to help manage application state (for highlighting links, changing panels, etc.)

Maybe I'm missing something, but the way I would go about this is to listen to route changes and then update some state. These changes would then propagate down to React UI.

**Comment by Guria** [comment]
Could you descrobe your case?

**Comment by Guria** [comment]
Just use signals bound to routes to set some state in tree.
