### ISSUE TITLE
Issue with .getUrl() from signal to get a route's url

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral-module-router#91]
Per the documentation here: http://www.cerebraljs.com/routing/hyperlinks, it says that hyperlinks are possible by using `getUrl()` on a signal. It doesn't look like the method is getting attached to the signal, though. 

Perhaps the documentation is out-dated or I'm doing something wrong? I'm getting a `getUrl is not a function` type error.

Here's a quick test repo: https://github.com/awei01/cerebral-module-router-getUrl-bug

**Comment by Guria** [comment]
cerebraljs.com documentation for router is slightly outdated. website is currently preparing for great update. for now just follow this repo readme for actual docs:
https://github.com/cerebral/cerebral-module-router#create-links

**Comment by awei01** [comment]
Ok, thx.

**Comment by awei01** [comment]
Hi, sorry, but I had another question on this. 

How is it possible to access the router service from the view? It doesn't appear that the `this.props.modules` object is populated with services.

**Comment by Guria** [comment]
It depends on which view you are using. React one populates controller in context. Btw, cerebral-view-react has a Link compnent, which is might be what are you trying to the nd actualy.

**Comment by awei01** [comment]
Ok, thanks. `context.controller` helps.
