### ISSUE TITLE
Possible compatibility issue with cerebral-module-devtools and this module

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral-module-router#95]
Example repo: 
https://github.com/awei01/cerebral-devtools-router-test

Basic summary: When using the devtools and storing predefinedSignals, when refreshing the application, router parameters are not preserved in the URL.

**Comment by Guria** [comment]
@awei01 great catch, thanks. it is not about devtools, but about changed way of passing signal info in `cerebral@0.34`. Fix is on the way.
